### ISSUE TITLE
Reproduce the CLRP paper results

### ISSUE THREAD

**Issue by hayabrama** [jurgyy/CLRP#2]
Hi!
I also tried to implement the CLRP method and failed to reproduce the results. When looking for a solution I found your notebook, and wanted to ask if you had any progress? Have you managed to contact the authors? I sent an email to one of them but it was never answered... 
Thanks! 
Haya

**Comment by JindongGu** [comment]
> Hi!
> I also tried to implement the CLRP method and failed to reproduce the results. When looking for a solution I found your notebook, and wanted to ask if you had any progress? Have you managed to contact the authors? I sent an email to one of them but it was never answered...
> Thanks!
> Haya

Hi there, it might go to my Spam, sorry for that! I published my code long time ago. Heir is the link https://github.com/Jindong-Explainable-AI/CLRP. It may help you to reproduce the result. Thanks for your interest in our work. Bests!
Jindong

**Comment by hayabrama** [comment]
> > Hi!
> > I also tried to implement the CLRP method and failed to reproduce the results. When looking for a solution I found your notebook, and wanted to ask if you had any progress? Have you managed to contact the authors? I sent an email to one of them but it was never answered...
> > Thanks!
> > Haya
> 
> Hi there, it might go to my Spam, sorry for that! I published my code long time ago. Heir is the link https://github.com/Jindong-Explainable-AI/CLRP. It may help you to reproduce the result. Thanks for your interest in our work. Bests!
> Jindong

Thanks!
